//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceBem.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceNotificacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNotificacao() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECommerceBem.Core.Resource.ResourceNotificacao", typeof(ResourceNotificacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} está aguardando estoque..
        /// </summary>
        public static string PedidoAguardandoEstoque {
            get {
                return ResourceManager.GetString("PedidoAguardandoEstoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} foi cancelado com sucesso..
        /// </summary>
        public static string PedidoCancelado {
            get {
                return ResourceManager.GetString("PedidoCancelado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} foi concluido com sucesso!.
        /// </summary>
        public static string PedidoConcluido {
            get {
                return ResourceManager.GetString("PedidoConcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} foi criado com sucesso em {1}..
        /// </summary>
        public static string PedidoCriado {
            get {
                return ResourceManager.GetString("PedidoCriado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} foi cancelado e o estorno foi processado com sucesso..
        /// </summary>
        public static string PedidoEstornado {
            get {
                return ResourceManager.GetString("PedidoEstornado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} foi pago com sucesso!.
        /// </summary>
        public static string PedidoPago {
            get {
                return ResourceManager.GetString("PedidoPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu pedido com ID {0} está sendo processado para pagamento..
        /// </summary>
        public static string PedidoProcessado {
            get {
                return ResourceManager.GetString("PedidoProcessado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido com ID {0} está sem estoque..
        /// </summary>
        public static string PedidoSemEtoque {
            get {
                return ResourceManager.GetString("PedidoSemEtoque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido com ID {0} está sendo separado para envio..
        /// </summary>
        public static string PedidoSeparado {
            get {
                return ResourceManager.GetString("PedidoSeparado", resourceCulture);
            }
        }
    }
}
